name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cache-toolchains-posix:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            src/third_party/llvm-build/Release+Asserts/
            src/gn/
            src/qemu-user*.deb
          key: toolchains-posix-${{ hashFiles('CHROMIUM_VERSION') }}
      - run: sudo apt update && sudo apt install ninja-build pkg-config ccache
      - run: ./get-clang.sh

  openwrt:
    needs: cache-toolchains-posix
    runs-on: ubuntu-22.04
    env:
      EXTRA_FLAGS: target_cpu="arm64" target_os="openwrt" arm_cpu="cortex-a53" build_static=true use_allocator_shim=false use_partition_alloc=false chrome_pgo_phase=0
      OPENWRT_FLAGS: arch=aarch64_cortex-a53-static target=sunxi subtarget=cortexa53 release=24.10.0 gcc_ver=13.3.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: src/third_party/llvm-build/Release+Asserts/
          key: toolchains-posix-${{ hashFiles('CHROMIUM_VERSION') }}

      - run: sudo apt update && sudo apt install ninja-build pkg-config ccache bubblewrap
      - run: ./get-clang.sh
      - run: ccache -z
      - run: ./build.sh
